services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./public/cdn.prod.website-files.com:/usr/share/nginx/html/cdn.prod.website-files.com
      - ./public/d3e54v103j8qbb.cloudfront.net:/usr/share/nginx/html/d3e54v103j8qbb.cloudfront.net
      - ./public/images:/usr/share/nginx/html/images
  