services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./public/cdn.prod.website-files.com:/usr/share/nginx/html/cdn.prod.website-files.com
      - ./public/d3e54v103j8qbb.cloudfront.net:/usr/share/nginx/html/d3e54v103j8qbb.cloudfront.net
      - ./public/images:/usr/share/nginx/html/images

  node:
    container_name: node
    image: node:22
    volumes:
      - ./bts-build.js:/app/bts-build.js
      - ./bts-server.js:/app/bts-server.js
      - ./src:/app/src
      - ./public/cdn.prod.website-files.com:/app/public/cdn.prod.website-files.com
      - ./public/d3e54v103j8qbb.cloudfront.net:/app/public/d3e54v103j8qbb.cloudfront.net
      - ./public/images:/app/public/images
      - ./routes.json:/app/routes.json
      - ./info.json:/app/info.json
      - ./package.json:/app/package.json
      - modules:/app/node_modules
    working_dir: /app
    command: >
      npm run dev
    restart: unless-stopped
    ports:
      - 3000:3000

volumes:
  modules: